language: cpp

compiler:
  - gcc
  - clang

cache: apt

# Forces gcc 4.8 for c++11 support
env:
  global:
    - GCC_VERSION="4.8"

git:
  submodules: false

addons:
  apt:
    packages:
      - freeglut3-dev
      - libopenal-dev
      - libalut-dev
      - libvorbis-dev
      - libogg-dev
      - liblua5.1-0-dev
      - libgettextpo-dev
      - libboost-all-dev
      - libqt4-opengl-dev
      - libglew-dev
      - cppcheck

before_install:
  # Force th update of the submodule manually
  - git submodule update --init --recursive --force --remote
  # Add gcc 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # Clang is not system wide.  This is a work around.
  - $CC --version
  - which $CC
  - export CC=`which $CC`

  - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz -O - | tar xz
  - (cd SDL2-2.0.5 && ./configure --prefix=/usr && sudo make -j`nproc` && sudo make install)
  - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz -O - | tar xz
  - (cd SDL2_image-2.0.1 && ./configure --prefix=/usr && sudo make -j`nproc` && sudo make install)
  - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz -O - | tar xz
  - (cd SDL2_ttf-2.0.14 && ./configure --prefix=/usr && sudo make -j`nproc` && sudo make install)

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq "libstdc++-${GCC_VERSION}-dev"; fi

script:
  - cmake -DCMAKE_CXX_COMPILER=$(which $CXX) -DDEBUG_FEATURES=ON .
  - make translations
  - make -j2 valyriatear

after_script: cppcheck --verbose --enable=all --quiet `git ls-files src/\*.cpp`
notifications:
  email:
    recipients:
      - yohann.ferreira@orange.fr
    on_success: change
    on_failure: always
