###################################
#   ValyriaTear                   #
#                                 #
#   AppVeyor build configuration  #
###################################

version: '{branch}-{build}'

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2013
clone_depth: 1

build:
  verbosity: minimal

environment:
  appveyor_build_worker_cloud: gce

init:
  - cmd: "IF \"%PLATFORM%\" == \"x86\" (set MINGWPATH=C:\\msys64\\mingw32\\bin& set MINGWPREFIX=mingw-w64-i686) ELSE (set MINGWPATH=C:\\msys64\\mingw64\\bin& set MINGWPREFIX=mingw-w64-x86_64)"

install:
  # Install NSIS
  - choco install nsis
  # Paths to MinGW/MSys2 environment + NSIS
  - cmd: "set PATH=C:\\Program Files (x86)\\NSIS;C:\\msys64\\usr\\bin;%MINGWPATH%;%PATH%"
  # Set up compiler
  - cmd: "set CC=%MINGWPATH%\\gcc.exe"
  - cmd: "set CXX=%MINGWPATH%\\g++.exe"
  # Update mirrors
  - cmd: "bash --login -c \"pacman --noconfirm --sync pacman pacman-mirrors\""
  # Update msys2 system (twice, first run does system packages)
  - cmd: "bash --login -c \"pacman -Su --noconfirm\""
  - cmd: "bash --login -c \"pacman -Su --noconfirm\""
  # Installed required libs
  - cmd: "bash --login -c \"pacman --noconfirm -S %MINGWPREFIX%-cmake %MINGWPREFIX%-ninja %MINGWPREFIX%-boost %MINGWPREFIX%-SDL2_ttf %MINGWPREFIX%-SDL2_image %MINGWPREFIX%-glew %MINGWPREFIX%-libpng %MINGWPREFIX%-libzip %MINGWPREFIX%-lua %MINGWPREFIX%-libogg %MINGWPREFIX%-libvorbis %MINGWPREFIX%-openal %MINGWPREFIX%-libiconv\""
  # Get the submodules
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  # Configure
  - cmd: "IF \"%configuration%\" == \"Debug\" (cmake -G \"Ninja\" -DDEBUG_FEATURES=on .) ELSE (cmake -G \"Ninja\" .)"
  # Compile
  - cmd: ninja

on_success:
 # Create installer
 - cmd: strip -sv %APPVEYOR_BUILD_FOLDER%\src\valyriatear.exe
 - cmd: "/X\"SetCompressor /FINAL lzma\" makensis.exe /DDLL_DIR="%MINGWPATH%" ValyriaTear.nsi"
 - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\valyriatear-win32-installer.exe

artifacts:
    - path: valyriatear-win32-installer.exe
      name: ValyriaTear Setup

platform:
  - x64
  - x86

configuration:
  - Release
  - Debug
